const express=require("express"),session=require("express-session"),multer=require("multer"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||10000;
const SCRIPT_URL=process.env.GOOGLE_SCRIPT_URL,SECRET=process.env.GOOGLE_SCRIPT_SECRET;
const ADMIN_EMAIL=process.env.ADMIN_EMAIL||"admin@example.com",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"change-me";
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024}});
app.set("view engine","ejs");app.use(express.urlencoded({extended:true,limit:"2mb"}));app.use(express.static("public"));
app.use(session({secret:process.env.SESSION_SECRET||crypto.randomBytes(32).toString("hex"),resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production"}}));
app.use((q,s,n)=>{s.locals.admin=!!q.session.admin;s.locals.appName="Juloos Volunteer Management System";n()});
async function api(x){if(!SCRIPT_URL||!SECRET)throw Error("Google Sheets backend is not configured.");let r=await fetch(SCRIPT_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...x,secret:SECRET})}),t=await r.text(),d;try{d=JSON.parse(t)}catch{throw Error("Invalid Google backend response.")}if(!r.ok||d.ok===false)throw Error(d.error||"Google backend error");return d}
function fp(f){return f?{name:f.originalname,mime:f.mimetype,data:f.buffer.toString("base64")}:null}
function admin(q,s,n){if(!q.session.admin)return s.redirect("/admin/login");n()}
app.get("/",(q,s)=>s.render("home",{title:"Home"}));app.get("/register",(q,s)=>s.render("register",{title:"Volunteer Registration",error:null}));
app.post("/register",upload.fields([{name:"photo",maxCount:1},{name:"aadhaar_file",maxCount:1}]),async(q,s)=>{try{let b=q.body,p=q.files?.photo?.[0],a=q.files?.aadhaar_file?.[0],an=String(b.aadhaar_number||"").replace(/\D/g,"");if(!b.name||!b.address||!b.phone||!b.emergency_phone||!b.age||an.length!==12||!p||!a||b.consent!=="yes")throw Error("Please complete all fields and select both files.");let r=await api({action:"register",volunteer:{name:b.name,address:b.address,phone:b.phone,emergency_phone:b.emergency_phone,age:Number(b.age),aadhaar_number:an,photo:fp(p),aadhaar_file:fp(a)}});s.render("submitted",{title:"Submitted",reg:r.registration_no})}catch(e){s.status(400).render("register",{title:"Volunteer Registration",error:e.message})}});
app.get("/status",(q,s)=>s.render("status",{title:"Status",result:null,error:null}));app.post("/status",async(q,s)=>{try{let r=await api({action:"status",registration_no:q.body.registration_no,phone:q.body.phone});s.render("status",{title:"Status",result:r.volunteer,error:r.volunteer?null:"Registration not found."})}catch(e){s.render("status",{title:"Status",result:null,error:e.message})}});
app.get("/admin/login",(q,s)=>s.render("login",{title:"Admin Login",error:null}));app.post("/admin/login",(q,s)=>{if(q.body.email===ADMIN_EMAIL&&q.body.password===ADMIN_PASSWORD){q.session.admin=true;return s.redirect("/admin")}s.status(401).render("login",{title:"Admin Login",error:"Invalid login."})});app.post("/logout",(q,s)=>q.session.destroy(()=>s.redirect("/")));
app.get("/admin",admin,async(q,s)=>{try{let r=await api({action:"list"});s.render("dashboard",{title:"Dashboard",stats:r.stats,rows:r.volunteers})}catch(e){s.render("error",{title:"Dashboard Error",message:e.message})}});
app.get("/admin/volunteer/:id",admin,async(q,s)=>{try{let r=await api({action:"get",id:q.params.id});if(!r.volunteer)return s.status(404).render("error",{title:"Not Found",message:"Volunteer not found"});s.render("volunteer",{title:"Review",v:r.volunteer})}catch(e){s.render("error",{title:"Error",message:e.message})}});
app.post("/admin/volunteer/:id/approve",admin,async(q,s)=>{try{await api({action:"approve",id:q.params.id});s.redirect("/admin/volunteer/"+q.params.id)}catch(e){s.render("error",{title:"Error",message:e.message})}});
app.post("/admin/volunteer/:id/reject",admin,async(q,s)=>{try{await api({action:"reject",id:q.params.id,reason:q.body.reason});s.redirect("/admin/volunteer/"+q.params.id)}catch(e){s.render("error",{title:"Error",message:e.message})}});
app.get("/admin/file/:id/:kind",admin,async(q,s)=>{try{let r=await api({action:"file",id:q.params.id,kind:q.params.kind});if(!r.file)return s.sendStatus(404);s.set("Content-Type",r.file.mime||"application/octet-stream");s.send(Buffer.from(r.file.data,"base64"))}catch(e){s.status(500).send(e.message)}});
app.get("/admin/id-card/:id",admin,async(q,s)=>{let r=await api({action:"get",id:q.params.id});if(!r.volunteer||r.volunteer.status!=="APPROVED")return s.status(404).render("error",{title:"Unavailable",message:"Not approved"});s.render("idcard",{title:"ID Card",v:r.volunteer})});
app.get("/verify/:vid",async(q,s)=>{let r=await api({action:"verify",volunteer_id:q.params.vid});s.render("verify",{title:"Verify",v:r.volunteer})});
app.use((e,q,s,n)=>s.status(500).render("error",{title:"Error",message:e.message}));
app.listen(PORT,()=>console.log("Juloos Volunteer System listening on "+PORT));