const SECRET="CHANGE_THIS_TO_A_LONG_RANDOM_SECRET",SHEET="Volunteers",FOLDER="Juloos Volunteer Uploads";
function doPost(e){try{let b=JSON.parse(e.postData.contents||"{}");if(b.secret!==SECRET)return out({ok:false,error:"Unauthorized"});let r={register:register,status:status,list:list,get:get,approve:approve,reject:reject,file:file,verify:verify}[b.action];if(!r)throw Error("Unknown action");return out(r(b))}catch(x){return out({ok:false,error:String(x.message||x)})}}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function sh(){let s=SpreadsheetApp.getActive();let x=s.getSheetByName(SHEET)||s.insertSheet(SHEET);if(x.getLastRow()==0)x.appendRow(["id","registration_no","volunteer_id","name","address","phone","emergency_phone","age","aadhaar_number","photo_id","photo_name","photo_mime","aadhaar_id","aadhaar_name","aadhaar_mime","status","rejection_reason","created_at","approved_at"]);return x}
function folder(){let p=PropertiesService.getScriptProperties(),id=p.getProperty("FOLDER_ID");if(id)try{return DriveApp.getFolderById(id)}catch(e){}let f=DriveApp.createFolder(FOLDER);p.setProperty("FOLDER_ID",f.getId());return f}
function save(f,n){if(!f||!f.data)throw Error("Missing upload");let bytes=Utilities.base64Decode(f.data);if(bytes.length>8*1024*1024)throw Error("File larger than 8 MB");let z=folder().createFile(Utilities.newBlob(bytes,f.mime||"application/octet-stream",n+"_"+f.name));return [z.getId(),z.getName(),z.getMimeType()]}
function rows(){let v=sh().getDataRange().getValues(),h=v[0];return v.slice(1).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}
function clean(o){if(!o)return null;return {id:o.id,registration_no:o.registration_no,volunteer_id:o.volunteer_id,name:o.name,address:o.address,phone:o.phone,emergency_phone:o.emergency_phone,age:o.age,status:o.status,rejection_reason:o.rejection_reason,aadhaar_masked:"XXXX XXXX "+String(o.aadhaar_number).slice(-4)}}
function register(b){let s=sh(),a=rows();if(a.some(x=>String(x.phone)==String(b.volunteer.phone)||String(x.aadhaar_number)==String(b.volunteer.aadhaar_number)))throw Error("Phone or Aadhaar already registered");let reg="JUL-"+Utilities.formatString("%06d",s.getLastRow()),p=save(b.volunteer.photo,"PHOTO_"+reg),d=save(b.volunteer.aadhaar_file,"AADHAAR_"+reg),id=String(Date.now());s.appendRow([id,reg,"",b.volunteer.name,b.volunteer.address,b.volunteer.phone,b.volunteer.emergency_phone,b.volunteer.age,b.volunteer.aadhaar_number,p[0],p[1],p[2],d[0],d[1],d[2],"PENDING","",new Date(),""]);return {ok:true,registration_no:reg}}
function find(id){return rows().find(x=>String(x.id)==String(id))}
function status(b){let o=rows().find(x=>String(x.registration_no).toUpperCase()==String(b.registration_no).toUpperCase()&&String(x.phone)==String(b.phone));return {ok:true,volunteer:clean(o)}}
function list(){let a=rows().reverse();return {ok:true,stats:{total:a.length,pending:a.filter(x=>x.status=="PENDING").length,approved:a.filter(x=>x.status=="APPROVED").length,rejected:a.filter(x=>x.status=="REJECTED").length},volunteers:a.map(clean)}}
function get(b){return {ok:true,volunteer:clean(find(b.id))}}
function update(b,st){let s=sh(),v=s.getDataRange().getValues(),h=v[0],r=v.findIndex(x=>String(x[h.indexOf("id")])==String(b.id));if(r<1)throw Error("Volunteer not found");s.getRange(r+1,h.indexOf("status")+1).setValue(st);s.getRange(r+1,h.indexOf("rejection_reason")+1).setValue(b.reason||"");if(st=="APPROVED"){s.getRange(r+1,h.indexOf("volunteer_id")+1).setValue("JUL-26-"+Utilities.formatString("%06d",r));s.getRange(r+1,h.indexOf("approved_at")+1).setValue(new Date())}return {ok:true}}
function approve(b){return update(b,"APPROVED")}function reject(b){return update(b,"REJECTED")}
function file(b){let o=find(b.id),id=b.kind=="photo"?o.photo_id:o.aadhaar_id,f=DriveApp.getFileById(id);return {ok:true,file:{name:f.getName(),mime:f.getMimeType(),data:Utilities.base64Encode(f.getBlob().getBytes())}}}
function verify(b){let o=rows().find(x=>String(x.volunteer_id)==String(b.volunteer_id)&&x.status=="APPROVED");return {ok:true,volunteer:o?{name:o.name,volunteer_id:o.volunteer_id,status:o.status}:null}}